// Code generated by goctl. DO NOT EDIT.
// Source: auths.proto

package authsclient

import (
	"context"

	"jijizhazha1024/go-mall/services/auths/auths"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AuthReq  = auths.AuthReq
	AuthsRes = auths.AuthsRes

	Auths interface {
		Authentication(ctx context.Context, in *AuthReq, opts ...grpc.CallOption) (*AuthsRes, error)
	}

	defaultAuths struct {
		cli zrpc.Client
	}
)

func NewAuths(cli zrpc.Client) Auths {
	return &defaultAuths{
		cli: cli,
	}
}

func (m *defaultAuths) Authentication(ctx context.Context, in *AuthReq, opts ...grpc.CallOption) (*AuthsRes, error) {
	client := auths.NewAuthsClient(m.cli.Conn())
	return client.Authentication(ctx, in, opts...)
}
