// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"database/sql"
)

type Cart struct {
	// 主键 自增
	ID int32
	// 创建时间
	CreatedAt sql.NullTime
	// 更新时间
	UpdatedAt sql.NullTime
	// 删除时间
	DeletedAt sql.NullTime
	// 用户ID
	UserID int32
	// 商品ID
	ProductID int32
	// 商品数量
	Quantity sql.NullInt32
	// 商品是否选中
	Checked sql.NullBool
}
