// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.5

package types

type DeleteRequest struct {
	UserId int64 `json:"user_id"`
}

type DeleteResponse struct {
	Code int64  `json:"code"`
	Msg  string `json:"msg"`
}

type GetInfoRequest struct {
	UserId int64 `json:"user_id"`
}

type GetInfoResponse struct {
	Code      int64  `json:"code"`
	Msg       string `json:"msg"`
	UserId    int64  `json:"user_id"`
	LogoutAt  int64  `json:"logout_at"`
	CreatedAt int64  `json:"created_at"`
	UpdateAt  int64  `json:"update_at"`
	Email     string `json:"email"`
	UserName  string `json:"user_name"`
}

type LoginRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Code         int64  `json:"code"`
	Msg          string `json:"msg"`
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
}

type LogoutRequest struct {
	UserId int64 `json:"user_id"`
}

type LogoutResponse struct {
	Code int64  `json:"code"`
	Msg  string `json:"msg"`
}

type RegisterRequest struct {
	Email           string `json:"email"`
	Password        string `json:"password"`
	ConfirmPassword string `json:"confirmPassword"`
}

type RegisterResponse struct {
	Code         int64  `json:"code"`
	Msg          string `json:"msg"`
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
}

type UpdateRequest struct {
	UserName string `json:"user_name"`
}

type UpdateResponse struct {
	Code     int64  `json:"code"`
	Msg      string `json:"msg"`
	UserName string `json:"user_name"`
	UpdateAt int64  `json:"update_at"`
}
