// Code generated by goctl. DO NOT EDIT.
// Source: auths.proto

package server

import (
	"context"

	"jijizhazha1024/go-mall/services/auths/auths"
	"jijizhazha1024/go-mall/services/auths/internal/logic"
	"jijizhazha1024/go-mall/services/auths/internal/svc"
)

type AuthsServer struct {
	svcCtx *svc.ServiceContext
	auths.UnimplementedAuthsServer
}

func NewAuthsServer(svcCtx *svc.ServiceContext) *AuthsServer {
	return &AuthsServer{
		svcCtx: svcCtx,
	}
}

func (s *AuthsServer) Authentication(ctx context.Context, in *auths.AuthReq) (*auths.AuthsRes, error) {
	l := logic.NewAuthenticationLogic(ctx, s.svcCtx)
	return l.Authentication(in)
}
