// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.19.4
// source: coupons.proto

package coupons

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 优惠券信息
type Coupon struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                 // 优惠券ID
	Name           string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                             // 券名称
	Type           int32  `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`                                            // 类型：1-满减 2-折扣 3-立减
	Value          int32  `protobuf:"varint,4,opt,name=value,proto3" json:"value,omitempty"`                                          // 优惠值（根据类型：分/百分比）
	MinAmount      int32  `protobuf:"varint,5,opt,name=min_amount,json=minAmount,proto3" json:"min_amount,omitempty"`                 // 最低消费金额（分）
	StartTime      string `protobuf:"bytes,6,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`                  // 有效期开始
	EndTime        string `protobuf:"bytes,7,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`                        // 有效期结束
	Status         int32  `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`                                        // 状态：0-禁用 1-启用
	TotalCount     int32  `protobuf:"varint,9,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`              // 发行总量
	RemainingCount int32  `protobuf:"varint,10,opt,name=remaining_count,json=remainingCount,proto3" json:"remaining_count,omitempty"` // 剩余数量
	CreatedAt      string `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                 // 创建时间
	UpdatedAt      string `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`                 // 更新时间
}

func (x *Coupon) Reset() {
	*x = Coupon{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coupons_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Coupon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Coupon) ProtoMessage() {}

func (x *Coupon) ProtoReflect() protoreflect.Message {
	mi := &file_coupons_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Coupon.ProtoReflect.Descriptor instead.
func (*Coupon) Descriptor() ([]byte, []int) {
	return file_coupons_proto_rawDescGZIP(), []int{0}
}

func (x *Coupon) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Coupon) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Coupon) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Coupon) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Coupon) GetMinAmount() int32 {
	if x != nil {
		return x.MinAmount
	}
	return 0
}

func (x *Coupon) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *Coupon) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *Coupon) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Coupon) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *Coupon) GetRemainingCount() int32 {
	if x != nil {
		return x.RemainingCount
	}
	return 0
}

func (x *Coupon) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Coupon) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// 用户优惠券信息
type UserCoupon struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                               // 用户优惠券ID
	UserId    int32  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`         // 用户ID
	CouponId  string `protobuf:"bytes,3,opt,name=coupon_id,json=couponId,proto3" json:"coupon_id,omitempty"`    // 优惠券ID
	Status    int32  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`                       // 状态：0-未使用 1-已使用 2-已过期
	OrderId   string `protobuf:"bytes,5,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`       // 使用的订单ID
	UsedAt    string `protobuf:"bytes,6,opt,name=used_at,json=usedAt,proto3" json:"used_at,omitempty"`          // 使用时间
	CreatedAt string `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // 创建时间
	UpdatedAt string `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // 更新时间
}

func (x *UserCoupon) Reset() {
	*x = UserCoupon{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coupons_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserCoupon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCoupon) ProtoMessage() {}

func (x *UserCoupon) ProtoReflect() protoreflect.Message {
	mi := &file_coupons_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCoupon.ProtoReflect.Descriptor instead.
func (*UserCoupon) Descriptor() ([]byte, []int) {
	return file_coupons_proto_rawDescGZIP(), []int{1}
}

func (x *UserCoupon) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserCoupon) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserCoupon) GetCouponId() string {
	if x != nil {
		return x.CouponId
	}
	return ""
}

func (x *UserCoupon) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UserCoupon) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *UserCoupon) GetUsedAt() string {
	if x != nil {
		return x.UsedAt
	}
	return ""
}

func (x *UserCoupon) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *UserCoupon) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// 优惠券使用记录
type CouponUsage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                               // 使用记录ID
	OrderId        string `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`                       // 关联的订单ID
	CouponId       string `protobuf:"bytes,3,opt,name=coupon_id,json=couponId,proto3" json:"coupon_id,omitempty"`                    // 优惠券ID
	UserId         int32  `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                         // 用户ID
	CouponType     int32  `protobuf:"varint,5,opt,name=coupon_type,json=couponType,proto3" json:"coupon_type,omitempty"`             // 当时优惠券类型：1-满减 2-折扣 3-立减
	OriginValue    int32  `protobuf:"varint,6,opt,name=origin_value,json=originValue,proto3" json:"origin_value,omitempty"`          // 当时优惠值（根据类型：分/百分比）
	DiscountAmount int32  `protobuf:"varint,7,opt,name=discount_amount,json=discountAmount,proto3" json:"discount_amount,omitempty"` // 抵扣金额（分）
	AppliedAt      string `protobuf:"bytes,8,opt,name=applied_at,json=appliedAt,proto3" json:"applied_at,omitempty"`                 // 应用时间
}

func (x *CouponUsage) Reset() {
	*x = CouponUsage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coupons_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CouponUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CouponUsage) ProtoMessage() {}

func (x *CouponUsage) ProtoReflect() protoreflect.Message {
	mi := &file_coupons_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CouponUsage.ProtoReflect.Descriptor instead.
func (*CouponUsage) Descriptor() ([]byte, []int) {
	return file_coupons_proto_rawDescGZIP(), []int{2}
}

func (x *CouponUsage) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CouponUsage) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CouponUsage) GetCouponId() string {
	if x != nil {
		return x.CouponId
	}
	return ""
}

func (x *CouponUsage) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CouponUsage) GetCouponType() int32 {
	if x != nil {
		return x.CouponType
	}
	return 0
}

func (x *CouponUsage) GetOriginValue() int32 {
	if x != nil {
		return x.OriginValue
	}
	return 0
}

func (x *CouponUsage) GetDiscountAmount() int32 {
	if x != nil {
		return x.DiscountAmount
	}
	return 0
}

func (x *CouponUsage) GetAppliedAt() string {
	if x != nil {
		return x.AppliedAt
	}
	return ""
}

// 分页请求
type PaginationReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page  int32 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`   // 页码
	Limit int32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"` // 每页记录数
}

func (x *PaginationReq) Reset() {
	*x = PaginationReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coupons_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaginationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationReq) ProtoMessage() {}

func (x *PaginationReq) ProtoReflect() protoreflect.Message {
	mi := &file_coupons_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationReq.ProtoReflect.Descriptor instead.
func (*PaginationReq) Descriptor() ([]byte, []int) {
	return file_coupons_proto_rawDescGZIP(), []int{3}
}

func (x *PaginationReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PaginationReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// 获取优惠券列表请求
type ListCouponsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pagination *PaginationReq `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Type       int32          `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`     // 可选：优惠券类型
	Status     int32          `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"` // 可选：优惠券状态
}

func (x *ListCouponsReq) Reset() {
	*x = ListCouponsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coupons_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListCouponsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCouponsReq) ProtoMessage() {}

func (x *ListCouponsReq) ProtoReflect() protoreflect.Message {
	mi := &file_coupons_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCouponsReq.ProtoReflect.Descriptor instead.
func (*ListCouponsReq) Descriptor() ([]byte, []int) {
	return file_coupons_proto_rawDescGZIP(), []int{4}
}

func (x *ListCouponsReq) GetPagination() *PaginationReq {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListCouponsReq) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *ListCouponsReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// 获取优惠券列表响应
type ListCouponsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Coupons    []*Coupon `protobuf:"bytes,1,rep,name=coupons,proto3" json:"coupons,omitempty"`
	TotalCount int32     `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
}

func (x *ListCouponsResp) Reset() {
	*x = ListCouponsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coupons_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListCouponsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCouponsResp) ProtoMessage() {}

func (x *ListCouponsResp) ProtoReflect() protoreflect.Message {
	mi := &file_coupons_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCouponsResp.ProtoReflect.Descriptor instead.
func (*ListCouponsResp) Descriptor() ([]byte, []int) {
	return file_coupons_proto_rawDescGZIP(), []int{5}
}

func (x *ListCouponsResp) GetCoupons() []*Coupon {
	if x != nil {
		return x.Coupons
	}
	return nil
}

func (x *ListCouponsResp) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// 获取单个优惠券请求
type GetCouponReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // 优惠券ID
}

func (x *GetCouponReq) Reset() {
	*x = GetCouponReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coupons_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCouponReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCouponReq) ProtoMessage() {}

func (x *GetCouponReq) ProtoReflect() protoreflect.Message {
	mi := &file_coupons_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCouponReq.ProtoReflect.Descriptor instead.
func (*GetCouponReq) Descriptor() ([]byte, []int) {
	return file_coupons_proto_rawDescGZIP(), []int{6}
}

func (x *GetCouponReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// 获取单个优惠券响应
type GetCouponResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Coupon *Coupon `protobuf:"bytes,1,opt,name=coupon,proto3" json:"coupon,omitempty"`
}

func (x *GetCouponResp) Reset() {
	*x = GetCouponResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coupons_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCouponResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCouponResp) ProtoMessage() {}

func (x *GetCouponResp) ProtoReflect() protoreflect.Message {
	mi := &file_coupons_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCouponResp.ProtoReflect.Descriptor instead.
func (*GetCouponResp) Descriptor() ([]byte, []int) {
	return file_coupons_proto_rawDescGZIP(), []int{7}
}

func (x *GetCouponResp) GetCoupon() *Coupon {
	if x != nil {
		return x.Coupon
	}
	return nil
}

// 创建优惠券请求
type CreateCouponReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Coupon *Coupon `protobuf:"bytes,1,opt,name=coupon,proto3" json:"coupon,omitempty"`
}

func (x *CreateCouponReq) Reset() {
	*x = CreateCouponReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coupons_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateCouponReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCouponReq) ProtoMessage() {}

func (x *CreateCouponReq) ProtoReflect() protoreflect.Message {
	mi := &file_coupons_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCouponReq.ProtoReflect.Descriptor instead.
func (*CreateCouponReq) Descriptor() ([]byte, []int) {
	return file_coupons_proto_rawDescGZIP(), []int{8}
}

func (x *CreateCouponReq) GetCoupon() *Coupon {
	if x != nil {
		return x.Coupon
	}
	return nil
}

// 创建优惠券响应
type CreateCouponResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // 创建的优惠券ID
}

func (x *CreateCouponResp) Reset() {
	*x = CreateCouponResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coupons_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateCouponResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCouponResp) ProtoMessage() {}

func (x *CreateCouponResp) ProtoReflect() protoreflect.Message {
	mi := &file_coupons_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCouponResp.ProtoReflect.Descriptor instead.
func (*CreateCouponResp) Descriptor() ([]byte, []int) {
	return file_coupons_proto_rawDescGZIP(), []int{9}
}

func (x *CreateCouponResp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// 更新优惠券请求
type UpdateCouponReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`         // 优惠券ID
	Coupon *Coupon `protobuf:"bytes,2,opt,name=coupon,proto3" json:"coupon,omitempty"` // 更新的优惠券信息
}

func (x *UpdateCouponReq) Reset() {
	*x = UpdateCouponReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coupons_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateCouponReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCouponReq) ProtoMessage() {}

func (x *UpdateCouponReq) ProtoReflect() protoreflect.Message {
	mi := &file_coupons_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCouponReq.ProtoReflect.Descriptor instead.
func (*UpdateCouponReq) Descriptor() ([]byte, []int) {
	return file_coupons_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateCouponReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateCouponReq) GetCoupon() *Coupon {
	if x != nil {
		return x.Coupon
	}
	return nil
}

// 更新优惠券响应
type UpdateCouponResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 更新结果
}

func (x *UpdateCouponResp) Reset() {
	*x = UpdateCouponResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coupons_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateCouponResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCouponResp) ProtoMessage() {}

func (x *UpdateCouponResp) ProtoReflect() protoreflect.Message {
	mi := &file_coupons_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCouponResp.ProtoReflect.Descriptor instead.
func (*UpdateCouponResp) Descriptor() ([]byte, []int) {
	return file_coupons_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateCouponResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 删除优惠券请求
type DeleteCouponReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // 优惠券ID
}

func (x *DeleteCouponReq) Reset() {
	*x = DeleteCouponReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coupons_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteCouponReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCouponReq) ProtoMessage() {}

func (x *DeleteCouponReq) ProtoReflect() protoreflect.Message {
	mi := &file_coupons_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCouponReq.ProtoReflect.Descriptor instead.
func (*DeleteCouponReq) Descriptor() ([]byte, []int) {
	return file_coupons_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteCouponReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// 删除优惠券响应
type DeleteCouponResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 删除结果
}

func (x *DeleteCouponResp) Reset() {
	*x = DeleteCouponResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coupons_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteCouponResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCouponResp) ProtoMessage() {}

func (x *DeleteCouponResp) ProtoReflect() protoreflect.Message {
	mi := &file_coupons_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCouponResp.ProtoReflect.Descriptor instead.
func (*DeleteCouponResp) Descriptor() ([]byte, []int) {
	return file_coupons_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteCouponResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 获取用户优惠券列表请求
type ListUserCouponsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId     int32          `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用户ID
	Pagination *PaginationReq `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Status     int32          `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"` // 可选：优惠券状态
}

func (x *ListUserCouponsReq) Reset() {
	*x = ListUserCouponsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coupons_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListUserCouponsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserCouponsReq) ProtoMessage() {}

func (x *ListUserCouponsReq) ProtoReflect() protoreflect.Message {
	mi := &file_coupons_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserCouponsReq.ProtoReflect.Descriptor instead.
func (*ListUserCouponsReq) Descriptor() ([]byte, []int) {
	return file_coupons_proto_rawDescGZIP(), []int{14}
}

func (x *ListUserCouponsReq) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListUserCouponsReq) GetPagination() *PaginationReq {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListUserCouponsReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// 获取用户优惠券列表响应
type ListUserCouponsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserCoupons []*UserCoupon `protobuf:"bytes,1,rep,name=user_coupons,json=userCoupons,proto3" json:"user_coupons,omitempty"`
	TotalCount  int32         `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
}

func (x *ListUserCouponsResp) Reset() {
	*x = ListUserCouponsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coupons_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListUserCouponsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserCouponsResp) ProtoMessage() {}

func (x *ListUserCouponsResp) ProtoReflect() protoreflect.Message {
	mi := &file_coupons_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserCouponsResp.ProtoReflect.Descriptor instead.
func (*ListUserCouponsResp) Descriptor() ([]byte, []int) {
	return file_coupons_proto_rawDescGZIP(), []int{15}
}

func (x *ListUserCouponsResp) GetUserCoupons() []*UserCoupon {
	if x != nil {
		return x.UserCoupons
	}
	return nil
}

func (x *ListUserCouponsResp) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// 获取用户优惠券详情请求
type GetUserCouponReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // 用户优惠券ID
}

func (x *GetUserCouponReq) Reset() {
	*x = GetUserCouponReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coupons_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserCouponReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserCouponReq) ProtoMessage() {}

func (x *GetUserCouponReq) ProtoReflect() protoreflect.Message {
	mi := &file_coupons_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserCouponReq.ProtoReflect.Descriptor instead.
func (*GetUserCouponReq) Descriptor() ([]byte, []int) {
	return file_coupons_proto_rawDescGZIP(), []int{16}
}

func (x *GetUserCouponReq) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 获取用户优惠券详情响应
type GetUserCouponResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserCoupon *UserCoupon `protobuf:"bytes,1,opt,name=user_coupon,json=userCoupon,proto3" json:"user_coupon,omitempty"`
}

func (x *GetUserCouponResp) Reset() {
	*x = GetUserCouponResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coupons_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserCouponResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserCouponResp) ProtoMessage() {}

func (x *GetUserCouponResp) ProtoReflect() protoreflect.Message {
	mi := &file_coupons_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserCouponResp.ProtoReflect.Descriptor instead.
func (*GetUserCouponResp) Descriptor() ([]byte, []int) {
	return file_coupons_proto_rawDescGZIP(), []int{17}
}

func (x *GetUserCouponResp) GetUserCoupon() *UserCoupon {
	if x != nil {
		return x.UserCoupon
	}
	return nil
}

// 用户领取优惠券请求
type ClaimCouponReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   int32  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`      // 用户ID
	CouponId string `protobuf:"bytes,2,opt,name=coupon_id,json=couponId,proto3" json:"coupon_id,omitempty"` // 优惠券ID
}

func (x *ClaimCouponReq) Reset() {
	*x = ClaimCouponReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coupons_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClaimCouponReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimCouponReq) ProtoMessage() {}

func (x *ClaimCouponReq) ProtoReflect() protoreflect.Message {
	mi := &file_coupons_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimCouponReq.ProtoReflect.Descriptor instead.
func (*ClaimCouponReq) Descriptor() ([]byte, []int) {
	return file_coupons_proto_rawDescGZIP(), []int{18}
}

func (x *ClaimCouponReq) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ClaimCouponReq) GetCouponId() string {
	if x != nil {
		return x.CouponId
	}
	return ""
}

// 用户领取优惠券响应
type ClaimCouponResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 领取结果
}

func (x *ClaimCouponResp) Reset() {
	*x = ClaimCouponResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coupons_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClaimCouponResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimCouponResp) ProtoMessage() {}

func (x *ClaimCouponResp) ProtoReflect() protoreflect.Message {
	mi := &file_coupons_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimCouponResp.ProtoReflect.Descriptor instead.
func (*ClaimCouponResp) Descriptor() ([]byte, []int) {
	return file_coupons_proto_rawDescGZIP(), []int{19}
}

func (x *ClaimCouponResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 使用优惠券请求
type UseCouponReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   int32  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`      // 用户ID
	CouponId string `protobuf:"bytes,2,opt,name=coupon_id,json=couponId,proto3" json:"coupon_id,omitempty"` // 优惠券ID
	OrderId  string `protobuf:"bytes,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`    // 订单ID
}

func (x *UseCouponReq) Reset() {
	*x = UseCouponReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coupons_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UseCouponReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseCouponReq) ProtoMessage() {}

func (x *UseCouponReq) ProtoReflect() protoreflect.Message {
	mi := &file_coupons_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseCouponReq.ProtoReflect.Descriptor instead.
func (*UseCouponReq) Descriptor() ([]byte, []int) {
	return file_coupons_proto_rawDescGZIP(), []int{20}
}

func (x *UseCouponReq) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UseCouponReq) GetCouponId() string {
	if x != nil {
		return x.CouponId
	}
	return ""
}

func (x *UseCouponReq) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

// 使用优惠券响应
type UseCouponResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success        bool  `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                                     // 使用结果
	DiscountAmount int32 `protobuf:"varint,2,opt,name=discount_amount,json=discountAmount,proto3" json:"discount_amount,omitempty"` // 抵扣金额（分）
}

func (x *UseCouponResp) Reset() {
	*x = UseCouponResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coupons_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UseCouponResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseCouponResp) ProtoMessage() {}

func (x *UseCouponResp) ProtoReflect() protoreflect.Message {
	mi := &file_coupons_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseCouponResp.ProtoReflect.Descriptor instead.
func (*UseCouponResp) Descriptor() ([]byte, []int) {
	return file_coupons_proto_rawDescGZIP(), []int{21}
}

func (x *UseCouponResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UseCouponResp) GetDiscountAmount() int32 {
	if x != nil {
		return x.DiscountAmount
	}
	return 0
}

// 获取优惠券使用记录请求
type ListCouponUsagesReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CouponId   string         `protobuf:"bytes,1,opt,name=coupon_id,json=couponId,proto3" json:"coupon_id,omitempty"` // 优惠券ID
	Pagination *PaginationReq `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (x *ListCouponUsagesReq) Reset() {
	*x = ListCouponUsagesReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coupons_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListCouponUsagesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCouponUsagesReq) ProtoMessage() {}

func (x *ListCouponUsagesReq) ProtoReflect() protoreflect.Message {
	mi := &file_coupons_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCouponUsagesReq.ProtoReflect.Descriptor instead.
func (*ListCouponUsagesReq) Descriptor() ([]byte, []int) {
	return file_coupons_proto_rawDescGZIP(), []int{22}
}

func (x *ListCouponUsagesReq) GetCouponId() string {
	if x != nil {
		return x.CouponId
	}
	return ""
}

func (x *ListCouponUsagesReq) GetPagination() *PaginationReq {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// 获取优惠券使用记录响应
type ListCouponUsagesResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Usages     []*CouponUsage `protobuf:"bytes,1,rep,name=usages,proto3" json:"usages,omitempty"`
	TotalCount int32          `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
}

func (x *ListCouponUsagesResp) Reset() {
	*x = ListCouponUsagesResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coupons_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListCouponUsagesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCouponUsagesResp) ProtoMessage() {}

func (x *ListCouponUsagesResp) ProtoReflect() protoreflect.Message {
	mi := &file_coupons_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCouponUsagesResp.ProtoReflect.Descriptor instead.
func (*ListCouponUsagesResp) Descriptor() ([]byte, []int) {
	return file_coupons_proto_rawDescGZIP(), []int{23}
}

func (x *ListCouponUsagesResp) GetUsages() []*CouponUsage {
	if x != nil {
		return x.Usages
	}
	return nil
}

func (x *ListCouponUsagesResp) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

var File_coupons_proto protoreflect.FileDescriptor

var file_coupons_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x73, 0x22, 0xcf, 0x02, 0x0a, 0x06, 0x43, 0x6f, 0x75,
	0x70, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x69, 0x6e, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6d, 0x69, 0x6e, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12,
	0x19, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x27, 0x0a, 0x0f, 0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67,
	0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x72, 0x65,
	0x6d, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0xdc, 0x01, 0x0a, 0x0a, 0x55,
	0x73, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x49, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0xfa, 0x01, 0x0a, 0x0b, 0x43, 0x6f,
	0x75, 0x70, 0x6f, 0x6e, 0x55, 0x73, 0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x5f, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x49,
	0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x6f,
	0x75, 0x70, 0x6f, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0a, 0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x6f,
	0x72, 0x69, 0x67, 0x69, 0x6e, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0b, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x27,
	0x0a, 0x0f, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x70, 0x70, 0x6c, 0x69,
	0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x70, 0x70,
	0x6c, 0x69, 0x65, 0x64, 0x41, 0x74, 0x22, 0x39, 0x0a, 0x0d, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c,
	0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69,
	0x74, 0x22, 0x74, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x73,
	0x52, 0x65, 0x71, 0x12, 0x36, 0x0a, 0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e,
	0x73, 0x2e, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x52,
	0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x5d, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74, 0x43,
	0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x29, 0x0a, 0x07, 0x63, 0x6f,
	0x75, 0x70, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x63, 0x6f,
	0x75, 0x70, 0x6f, 0x6e, 0x73, 0x2e, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x52, 0x07, 0x63, 0x6f,
	0x75, 0x70, 0x6f, 0x6e, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x1e, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x75,
	0x70, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x38, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x75,
	0x70, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x27, 0x0a, 0x06, 0x63, 0x6f, 0x75, 0x70, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e,
	0x73, 0x2e, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x52, 0x06, 0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e,
	0x22, 0x3a, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x12, 0x27, 0x0a, 0x06, 0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x73, 0x2e, 0x43, 0x6f,
	0x75, 0x70, 0x6f, 0x6e, 0x52, 0x06, 0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x22, 0x22, 0x0a, 0x10,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x4a, 0x0a, 0x0f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x27, 0x0a, 0x06, 0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x73, 0x2e, 0x43, 0x6f,
	0x75, 0x70, 0x6f, 0x6e, 0x52, 0x06, 0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x22, 0x2c, 0x0a, 0x10,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x21, 0x0a, 0x0f, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x2c, 0x0a,
	0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x7d, 0x0a, 0x12, 0x4c,
	0x69, 0x73, 0x74, 0x55, 0x73, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x73, 0x52, 0x65,
	0x71, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x36, 0x0a, 0x0a, 0x70, 0x61,
	0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16,
	0x2e, 0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x73, 0x2e, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x52, 0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x6e, 0x0a, 0x13, 0x4c, 0x69,
	0x73, 0x74, 0x55, 0x73, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x36, 0x0a, 0x0c, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e,
	0x73, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x52, 0x0b, 0x75, 0x73,
	0x65, 0x72, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x22, 0x0a, 0x10, 0x47, 0x65,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x49,
	0x0a, 0x11, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x34, 0x0a, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x63, 0x6f, 0x75, 0x70,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x63, 0x6f, 0x75, 0x70, 0x6f,
	0x6e, 0x73, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x52, 0x0a, 0x75,
	0x73, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x22, 0x46, 0x0a, 0x0e, 0x43, 0x6c, 0x61,
	0x69, 0x6d, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x49,
	0x64, 0x22, 0x2b, 0x0a, 0x0f, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x5f,
	0x0a, 0x0c, 0x55, 0x73, 0x65, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x17,
	0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6f, 0x75, 0x70, 0x6f,
	0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6f, 0x75, 0x70,
	0x6f, 0x6e, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x22,
	0x52, 0x0a, 0x0d, 0x55, 0x73, 0x65, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x27, 0x0a, 0x0f, 0x64, 0x69,
	0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0e, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x41, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x22, 0x6a, 0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x75, 0x70, 0x6f,
	0x6e, 0x55, 0x73, 0x61, 0x67, 0x65, 0x73, 0x52, 0x65, 0x71, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6f,
	0x75, 0x70, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63,
	0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x36, 0x0a, 0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x63, 0x6f,
	0x75, 0x70, 0x6f, 0x6e, 0x73, 0x2e, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x52, 0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22,
	0x65, 0x0a, 0x14, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x55, 0x73, 0x61,
	0x67, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2c, 0x0a, 0x06, 0x75, 0x73, 0x61, 0x67, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e,
	0x73, 0x2e, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x55, 0x73, 0x61, 0x67, 0x65, 0x52, 0x06, 0x75,
	0x73, 0x61, 0x67, 0x65, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x32, 0xbb, 0x05, 0x0a, 0x07, 0x43, 0x6f, 0x75, 0x70, 0x6f,
	0x6e, 0x73, 0x12, 0x40, 0x0a, 0x0b, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e,
	0x73, 0x12, 0x17, 0x2e, 0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x73, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e, 0x63, 0x6f, 0x75,
	0x70, 0x6f, 0x6e, 0x73, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x3a, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x75, 0x70, 0x6f,
	0x6e, 0x12, 0x15, 0x2e, 0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x43,
	0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x63, 0x6f, 0x75, 0x70, 0x6f,
	0x6e, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x43, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e,
	0x12, 0x18, 0x2e, 0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x73, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x63, 0x6f, 0x75,
	0x70, 0x6f, 0x6e, 0x73, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x75, 0x70, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x43, 0x0a, 0x0c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43,
	0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x12, 0x18, 0x2e, 0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x73, 0x2e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x1a,
	0x19, 0x2e, 0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x73, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x43, 0x0a, 0x0c, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x12, 0x18, 0x2e, 0x63, 0x6f, 0x75,
	0x70, 0x6f, 0x6e, 0x73, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6f, 0x75, 0x70, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x73, 0x2e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x4c, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74, 0x55, 0x73, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x70, 0x6f,
	0x6e, 0x73, 0x12, 0x1b, 0x2e, 0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x73, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x1a,
	0x1c, 0x2e, 0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x73, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x55, 0x73,
	0x65, 0x72, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x46, 0x0a,
	0x0d, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x12, 0x19,
	0x2e, 0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72,
	0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x1a, 0x2e, 0x63, 0x6f, 0x75, 0x70,
	0x6f, 0x6e, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x70, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x40, 0x0a, 0x0b, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x43, 0x6f,
	0x75, 0x70, 0x6f, 0x6e, 0x12, 0x17, 0x2e, 0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x73, 0x2e, 0x43,
	0x6c, 0x61, 0x69, 0x6d, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e,
	0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x73, 0x2e, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x43, 0x6f, 0x75,
	0x70, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3a, 0x0a, 0x09, 0x55, 0x73, 0x65, 0x43, 0x6f,
	0x75, 0x70, 0x6f, 0x6e, 0x12, 0x15, 0x2e, 0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x73, 0x2e, 0x55,
	0x73, 0x65, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x63, 0x6f,
	0x75, 0x70, 0x6f, 0x6e, 0x73, 0x2e, 0x55, 0x73, 0x65, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x4f, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x75, 0x70, 0x6f,
	0x6e, 0x55, 0x73, 0x61, 0x67, 0x65, 0x73, 0x12, 0x1c, 0x2e, 0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e,
	0x73, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x55, 0x73, 0x61, 0x67,
	0x65, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x1d, 0x2e, 0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x73, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x55, 0x73, 0x61, 0x67, 0x65, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x2f, 0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e,
	0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_coupons_proto_rawDescOnce sync.Once
	file_coupons_proto_rawDescData = file_coupons_proto_rawDesc
)

func file_coupons_proto_rawDescGZIP() []byte {
	file_coupons_proto_rawDescOnce.Do(func() {
		file_coupons_proto_rawDescData = protoimpl.X.CompressGZIP(file_coupons_proto_rawDescData)
	})
	return file_coupons_proto_rawDescData
}

var file_coupons_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_coupons_proto_goTypes = []any{
	(*Coupon)(nil),               // 0: coupons.Coupon
	(*UserCoupon)(nil),           // 1: coupons.UserCoupon
	(*CouponUsage)(nil),          // 2: coupons.CouponUsage
	(*PaginationReq)(nil),        // 3: coupons.PaginationReq
	(*ListCouponsReq)(nil),       // 4: coupons.ListCouponsReq
	(*ListCouponsResp)(nil),      // 5: coupons.ListCouponsResp
	(*GetCouponReq)(nil),         // 6: coupons.GetCouponReq
	(*GetCouponResp)(nil),        // 7: coupons.GetCouponResp
	(*CreateCouponReq)(nil),      // 8: coupons.CreateCouponReq
	(*CreateCouponResp)(nil),     // 9: coupons.CreateCouponResp
	(*UpdateCouponReq)(nil),      // 10: coupons.UpdateCouponReq
	(*UpdateCouponResp)(nil),     // 11: coupons.UpdateCouponResp
	(*DeleteCouponReq)(nil),      // 12: coupons.DeleteCouponReq
	(*DeleteCouponResp)(nil),     // 13: coupons.DeleteCouponResp
	(*ListUserCouponsReq)(nil),   // 14: coupons.ListUserCouponsReq
	(*ListUserCouponsResp)(nil),  // 15: coupons.ListUserCouponsResp
	(*GetUserCouponReq)(nil),     // 16: coupons.GetUserCouponReq
	(*GetUserCouponResp)(nil),    // 17: coupons.GetUserCouponResp
	(*ClaimCouponReq)(nil),       // 18: coupons.ClaimCouponReq
	(*ClaimCouponResp)(nil),      // 19: coupons.ClaimCouponResp
	(*UseCouponReq)(nil),         // 20: coupons.UseCouponReq
	(*UseCouponResp)(nil),        // 21: coupons.UseCouponResp
	(*ListCouponUsagesReq)(nil),  // 22: coupons.ListCouponUsagesReq
	(*ListCouponUsagesResp)(nil), // 23: coupons.ListCouponUsagesResp
}
var file_coupons_proto_depIdxs = []int32{
	3,  // 0: coupons.ListCouponsReq.pagination:type_name -> coupons.PaginationReq
	0,  // 1: coupons.ListCouponsResp.coupons:type_name -> coupons.Coupon
	0,  // 2: coupons.GetCouponResp.coupon:type_name -> coupons.Coupon
	0,  // 3: coupons.CreateCouponReq.coupon:type_name -> coupons.Coupon
	0,  // 4: coupons.UpdateCouponReq.coupon:type_name -> coupons.Coupon
	3,  // 5: coupons.ListUserCouponsReq.pagination:type_name -> coupons.PaginationReq
	1,  // 6: coupons.ListUserCouponsResp.user_coupons:type_name -> coupons.UserCoupon
	1,  // 7: coupons.GetUserCouponResp.user_coupon:type_name -> coupons.UserCoupon
	3,  // 8: coupons.ListCouponUsagesReq.pagination:type_name -> coupons.PaginationReq
	2,  // 9: coupons.ListCouponUsagesResp.usages:type_name -> coupons.CouponUsage
	4,  // 10: coupons.Coupons.ListCoupons:input_type -> coupons.ListCouponsReq
	6,  // 11: coupons.Coupons.GetCoupon:input_type -> coupons.GetCouponReq
	8,  // 12: coupons.Coupons.CreateCoupon:input_type -> coupons.CreateCouponReq
	10, // 13: coupons.Coupons.UpdateCoupon:input_type -> coupons.UpdateCouponReq
	12, // 14: coupons.Coupons.DeleteCoupon:input_type -> coupons.DeleteCouponReq
	14, // 15: coupons.Coupons.ListUserCoupons:input_type -> coupons.ListUserCouponsReq
	16, // 16: coupons.Coupons.GetUserCoupon:input_type -> coupons.GetUserCouponReq
	18, // 17: coupons.Coupons.ClaimCoupon:input_type -> coupons.ClaimCouponReq
	20, // 18: coupons.Coupons.UseCoupon:input_type -> coupons.UseCouponReq
	22, // 19: coupons.Coupons.ListCouponUsages:input_type -> coupons.ListCouponUsagesReq
	5,  // 20: coupons.Coupons.ListCoupons:output_type -> coupons.ListCouponsResp
	7,  // 21: coupons.Coupons.GetCoupon:output_type -> coupons.GetCouponResp
	9,  // 22: coupons.Coupons.CreateCoupon:output_type -> coupons.CreateCouponResp
	11, // 23: coupons.Coupons.UpdateCoupon:output_type -> coupons.UpdateCouponResp
	13, // 24: coupons.Coupons.DeleteCoupon:output_type -> coupons.DeleteCouponResp
	15, // 25: coupons.Coupons.ListUserCoupons:output_type -> coupons.ListUserCouponsResp
	17, // 26: coupons.Coupons.GetUserCoupon:output_type -> coupons.GetUserCouponResp
	19, // 27: coupons.Coupons.ClaimCoupon:output_type -> coupons.ClaimCouponResp
	21, // 28: coupons.Coupons.UseCoupon:output_type -> coupons.UseCouponResp
	23, // 29: coupons.Coupons.ListCouponUsages:output_type -> coupons.ListCouponUsagesResp
	20, // [20:30] is the sub-list for method output_type
	10, // [10:20] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_coupons_proto_init() }
func file_coupons_proto_init() {
	if File_coupons_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_coupons_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Coupon); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_coupons_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*UserCoupon); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_coupons_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*CouponUsage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_coupons_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*PaginationReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_coupons_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*ListCouponsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_coupons_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*ListCouponsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_coupons_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*GetCouponReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_coupons_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*GetCouponResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_coupons_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*CreateCouponReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_coupons_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*CreateCouponResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_coupons_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateCouponReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_coupons_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateCouponResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_coupons_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteCouponReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_coupons_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteCouponResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_coupons_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*ListUserCouponsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_coupons_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*ListUserCouponsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_coupons_proto_msgTypes[16].Exporter = func(v any, i int) any {
			switch v := v.(*GetUserCouponReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_coupons_proto_msgTypes[17].Exporter = func(v any, i int) any {
			switch v := v.(*GetUserCouponResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_coupons_proto_msgTypes[18].Exporter = func(v any, i int) any {
			switch v := v.(*ClaimCouponReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_coupons_proto_msgTypes[19].Exporter = func(v any, i int) any {
			switch v := v.(*ClaimCouponResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_coupons_proto_msgTypes[20].Exporter = func(v any, i int) any {
			switch v := v.(*UseCouponReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_coupons_proto_msgTypes[21].Exporter = func(v any, i int) any {
			switch v := v.(*UseCouponResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_coupons_proto_msgTypes[22].Exporter = func(v any, i int) any {
			switch v := v.(*ListCouponUsagesReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_coupons_proto_msgTypes[23].Exporter = func(v any, i int) any {
			switch v := v.(*ListCouponUsagesResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_coupons_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_coupons_proto_goTypes,
		DependencyIndexes: file_coupons_proto_depIdxs,
		MessageInfos:      file_coupons_proto_msgTypes,
	}.Build()
	File_coupons_proto = out.File
	file_coupons_proto_rawDesc = nil
	file_coupons_proto_goTypes = nil
	file_coupons_proto_depIdxs = nil
}
