// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.5
// Source: carts.proto

package cartsclient

import (
	"context"

	"jijizhazha1024/go-mall/services/carts/carts"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CartInfoResponse     = carts.CartInfoResponse
	CartItemListResponse = carts.CartItemListResponse
	CartItemRequest      = carts.CartItemRequest
	EmptyCartResponse    = carts.EmptyCartResponse
	UserInfo             = carts.UserInfo

	Cart interface {
		CartItemList(ctx context.Context, in *UserInfo, opts ...grpc.CallOption) (*CartItemListResponse, error)
		CreateCartItem(ctx context.Context, in *CartItemRequest, opts ...grpc.CallOption) (*CartInfoResponse, error)
		UpdateCartItem(ctx context.Context, in *CartItemRequest, opts ...grpc.CallOption) (*EmptyCartResponse, error)
		DeleteCartItem(ctx context.Context, in *CartItemRequest, opts ...grpc.CallOption) (*EmptyCartResponse, error)
	}

	defaultCart struct {
		cli zrpc.Client
	}
)

func NewCart(cli zrpc.Client) Cart {
	return &defaultCart{
		cli: cli,
	}
}

func (m *defaultCart) CartItemList(ctx context.Context, in *UserInfo, opts ...grpc.CallOption) (*CartItemListResponse, error) {
	client := carts.NewCartClient(m.cli.Conn())
	return client.CartItemList(ctx, in, opts...)
}

func (m *defaultCart) CreateCartItem(ctx context.Context, in *CartItemRequest, opts ...grpc.CallOption) (*CartInfoResponse, error) {
	client := carts.NewCartClient(m.cli.Conn())
	return client.CreateCartItem(ctx, in, opts...)
}

func (m *defaultCart) UpdateCartItem(ctx context.Context, in *CartItemRequest, opts ...grpc.CallOption) (*EmptyCartResponse, error) {
	client := carts.NewCartClient(m.cli.Conn())
	return client.UpdateCartItem(ctx, in, opts...)
}

func (m *defaultCart) DeleteCartItem(ctx context.Context, in *CartItemRequest, opts ...grpc.CallOption) (*EmptyCartResponse, error) {
	client := carts.NewCartClient(m.cli.Conn())
	return client.DeleteCartItem(ctx, in, opts...)
}
