// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.19.4
// source: ai.proto

package ai

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	Ai_NLPExecutor_FullMethodName = "/ai.Ai/NLPExecutor"
)

// AiClient is the client API for Ai service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AiClient interface {
	NLPExecutor(ctx context.Context, in *NLPExecutorReq, opts ...grpc.CallOption) (*NLPExecutorResp, error)
}

type aiClient struct {
	cc grpc.ClientConnInterface
}

func NewAiClient(cc grpc.ClientConnInterface) AiClient {
	return &aiClient{cc}
}

func (c *aiClient) NLPExecutor(ctx context.Context, in *NLPExecutorReq, opts ...grpc.CallOption) (*NLPExecutorResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NLPExecutorResp)
	err := c.cc.Invoke(ctx, Ai_NLPExecutor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AiServer is the server API for Ai service.
// All implementations must embed UnimplementedAiServer
// for forward compatibility
type AiServer interface {
	NLPExecutor(context.Context, *NLPExecutorReq) (*NLPExecutorResp, error)
	mustEmbedUnimplementedAiServer()
}

// UnimplementedAiServer must be embedded to have forward compatible implementations.
type UnimplementedAiServer struct {
}

func (UnimplementedAiServer) NLPExecutor(context.Context, *NLPExecutorReq) (*NLPExecutorResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NLPExecutor not implemented")
}
func (UnimplementedAiServer) mustEmbedUnimplementedAiServer() {}

// UnsafeAiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AiServer will
// result in compilation errors.
type UnsafeAiServer interface {
	mustEmbedUnimplementedAiServer()
}

func RegisterAiServer(s grpc.ServiceRegistrar, srv AiServer) {
	s.RegisterService(&Ai_ServiceDesc, srv)
}

func _Ai_NLPExecutor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NLPExecutorReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiServer).NLPExecutor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ai_NLPExecutor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiServer).NLPExecutor(ctx, req.(*NLPExecutorReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Ai_ServiceDesc is the grpc.ServiceDesc for Ai service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Ai_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ai.Ai",
	HandlerType: (*AiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NLPExecutor",
			Handler:    _Ai_NLPExecutor_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ai.proto",
}
