// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.5
// Source: payment.proto

package server

import (
	"context"

	"jijizhazha1024/go-mall/services/payment/internal/logic"
	"jijizhazha1024/go-mall/services/payment/internal/svc"
	"jijizhazha1024/go-mall/services/payment/payment"
)

type PaymentServer struct {
	svcCtx *svc.ServiceContext
	payment.UnimplementedPaymentServer
}

func NewPaymentServer(svcCtx *svc.ServiceContext) *PaymentServer {
	return &PaymentServer{
		svcCtx: svcCtx,
	}
}

func (s *PaymentServer) CreatePayment(ctx context.Context, in *payment.PaymentReq) (*payment.PaymentResp, error) {
	l := logic.NewCreatePaymentLogic(ctx, s.svcCtx)
	return l.CreatePayment(in)
}

func (s *PaymentServer) ListPayments(ctx context.Context, in *payment.PaymentListReq) (*payment.PaymentListResp, error) {
	l := logic.NewListPaymentsLogic(ctx, s.svcCtx)
	return l.ListPayments(in)
}
