// Code generated by goctl. DO NOT EDIT.

package audit

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	auditFieldNames          = builder.RawFieldNames(&Audit{})
	auditRows                = strings.Join(auditFieldNames, ",")
	auditRowsExpectAutoSet   = strings.Join(stringx.Remove(auditFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	auditRowsWithPlaceHolder = strings.Join(stringx.Remove(auditFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	auditModel interface {
		Insert(ctx context.Context, data *Audit) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Audit, error)
		Update(ctx context.Context, data *Audit) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAuditModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Audit struct {
		Id                int64          `db:"id"`
		UserId            int64          `db:"user_id"`
		Username          string         `db:"username"`
		ActionType        string         `db:"action_type"`
		ActionDescription sql.NullString `db:"action_description"`
		TargetTable       string         `db:"target_table"`
		OldData           sql.NullString `db:"old_data"`
		NewData           sql.NullString `db:"new_data"`
		TargetId          sql.NullInt64  `db:"target_id"`
		IpAddress         sql.NullString `db:"ip_address"`
		TraceId           sql.NullString `db:"trace_id"`
		SpanId            sql.NullString `db:"span_id"`
		CreatedAt         time.Time      `db:"created_at"`
	}
)

func newAuditModel(conn sqlx.SqlConn) *defaultAuditModel {
	return &defaultAuditModel{
		conn:  conn,
		table: "`audit`",
	}
}

func (m *defaultAuditModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultAuditModel) FindOne(ctx context.Context, id int64) (*Audit, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", auditRows, m.table)
	var resp Audit
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAuditModel) Insert(ctx context.Context, data *Audit) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, auditRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.Username, data.ActionType, data.ActionDescription, data.TargetTable, data.OldData, data.NewData, data.TargetId, data.IpAddress, data.TraceId, data.SpanId)
	return ret, err
}

func (m *defaultAuditModel) Update(ctx context.Context, data *Audit) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, auditRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.UserId, data.Username, data.ActionType, data.ActionDescription, data.TargetTable, data.OldData, data.NewData, data.TargetId, data.IpAddress, data.TraceId, data.SpanId, data.Id)
	return err
}

func (m *defaultAuditModel) tableName() string {
	return m.table
}
