// Code generated by goctl. DO NOT EDIT.
// Source: ai.proto

package server

import (
	"context"

	"jijizhazha1024/go-mall/services/ai/ai"
	"jijizhazha1024/go-mall/services/ai/internal/logic"
	"jijizhazha1024/go-mall/services/ai/internal/svc"
)

type AiServer struct {
	svcCtx *svc.ServiceContext
	ai.UnimplementedAiServer
}

func NewAiServer(svcCtx *svc.ServiceContext) *AiServer {
	return &AiServer{
		svcCtx: svcCtx,
	}
}

func (s *AiServer) NLPExecutor(ctx context.Context, in *ai.NLPExecutorReq) (*ai.NLPExecutorResp, error) {
	l := logic.NewNLPExecutorLogic(ctx, s.svcCtx)
	return l.NLPExecutor(in)
}
