apiVersion: apps/v1
kind: Deployment
metadata:
  name: dtm
  namespace: go-mall
  labels:
    app: dtm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dtm
  template:
    metadata:
      labels:
        app: dtm
    spec:
      containers:
        - name: dtm
          image: yedf/dtm:latest
          imagePullPolicy: IfNotPresent
          args:
            - "-c=/app/dtm/configs/config.yaml"
          volumeMounts:
            - mountPath: /app/dtm/configs
              name: config
          ports:
            - containerPort: 36789
              protocol: TCP
              name: http
            - containerPort: 36790
              protocol: TCP
              name: grpc
          livenessProbe:
            httpGet:
              path: /api/ping
              port: 36789
              scheme: HTTP
          readinessProbe:
            httpGet:
              path: /api/ping
              port: 36789
              scheme: HTTP
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
      volumes:
        - name: config
          configMap:
            name: dtm-conf
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: go-mall
  name: dtm-conf
  labels:
    app: dtm
data:
  config.yaml: |-
    MicroService:
      Driver: 'dtm-driver-gozero' # 配置dtm使用go-zero的微服务协议
      Target: 'consul://124.71.72.124:8500/dtmservice' # 把dtm注册到consul的这个地址
      EndPoint: '0.0.0.0:36790'

---
apiVersion: v1
kind: Service
metadata:
  name: dtm-service
  namespace: go-mall
spec:
  selector:
    app: dtm  # 匹配Deployment的标签
  ports:
    - name: http
      port: 36789           # 集群内访问的端口
      targetPort: 36789  # 映射到容器端口
      nodePort: 30789
      protocol: TCP
  type: NodePort