Name: inventory.rpc
ListenOn: 0.0.0.0:10011
Mode: dev

# 服务发现
Consul:
  Host: 124.71.72.124:8500
  Key: inventory.rpc
  Meta:
    Protocol: grpc

Telemetry:
  Name: inventory.rpc
  Endpoint: http://124.71.72.124:14268/api/traces
  Batcher: jaeger
  Sampler: 1.0

Log:
  ServiceName: inventory-rpc
  Mode: console
  Encoding: json
  Path: ./logs/inventory-rpc

MysqlConfig:
  datasource: jjzzchtt:jjzzchtt@tcp(124.71.72.124:3306)/mall?charset=utf8mb4&parseTime=True&loc=Local

RedisConf:
  Host: 124.71.72.124:6379
  Pass: jjzzchtt
  Tls: false

RabbitMQConfig:
  Host: 124.71.72.124
  Port: 5672
  User: admin
  Pass: admin
  VHost: /