# 详细配置见：go-zero@v1.7.6\zrpc\config.go
Name: inventory.rpc
ListenOn: 0.0.0.0:10011 # 端口见接口文档
Mode: pro

# 服务发现
Consul:
  Host: ${CONSUL_HOST}
  Key: inventory.rpc # 与服务名称保持一致
  Meta:
    Protocol: grpc
  Tag:
    - grpc

MysqlConfig:
  datasource: ${MYSQL_DATA_SOURCE}

Log:
  ServiceName: inventory-rpc
  Mode: file
  Encoding: json
  Path: ./logs/inventory-rpc
  KeepDays: 30    # 保留30天日志
  Compress: true  # 启用日志压缩
  Rotation: size  # 按大小切割日志
  MaxSize: 100    # 每个日志文件最大100MB

# 指标监控配置
DevServer:
  Enabled: true
  Host: 0.0.0.0
  Port: 11000
  EnablePprof: false

# 链路追踪
Telemetry:
  Name: inventory.rpc # 与服务名称保持一致
  Endpoint: ${TRACES_ENDPOINT}
  Batcher: jaeger
  Sampler: 0.1 # 采样率，1.0表示全部采集, 0.1表示10%


RedisConf:
  Host: ${REDIS_HOST}
  Pass: ${REDIS_PASSWORD}
  Tls: false

RabbitMQConfig:
  Host: ${RABBITMQ_HOST}
  Port: ${RABBITMQ_PORT}
  User: ${RABBITMQ_USERNAME}
  Pass: ${RABBITMQ_PASSWORD}
  VHost: ${RABBITMQ_VHOST}