// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.5

package types

type CreateProductReq struct {
	Name        string   `json:"name"`
	Description string   `json:"description"`
	Picture     string   `json:"picture"`
	Stock       int64    `json:"stock"`
	Price       float64  `json:"price"`
	Categories  []string `json:"categories"`
}

type CreateProductResp struct {
	ProductID int64 `json:"product_id"`
}

type DeleteProductReq struct {
	ID int64 `path:"id"`
}

type DeleteProductResp struct {
	Success bool `json:"success"`
}

type GetProductReq struct {
	ID int64 `path:"id"`
}

type GetProductResp struct {
	ID          int64    `json:"id"`
	Name        string   `json:"name"`
	Description string   `json:"description"`
	Picture     string   `json:"picture"`
	Stock       int64    `json:"stock"`
	Price       float64  `json:"price"`
	Categories  []string `json:"categories"`
}

type UpdateProductReq struct {
	ID          int64    `json:"id"`
	Name        string   `json:"name,optional"`
	Description string   `json:"description,optional"`
	Picture     string   `json:"picture,optional"`
	Stock       int64    `json:"stock,optional"`
	Price       float64  `json:"price,optional"`
	Categories  []string `json:"categories,optional"`
}

type UpdateProductResp struct {
	ProductID int64 `json:"product_id"`
}
