// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.5

package types

type GetProductByIDReq struct {
	ID int64 ` json:"id"` // 商品ID（路径参数）
}

type GetProductByIDResp struct {
	ID          int64    `json:"id"`          // 商品ID
	Name        string   `json:"name"`        // 商品名称
	Description string   `json:"description"` // 商品描述
	Picture     string   `json:"picture"`     // 商品图片URL
	Stock       int64    `json:"stock"`       // 商品库存
	Price       float64  `json:"price"`       // 商品价格
	Categories  []string `json:"categories"`  // 商品分类
}

type GetProductListReq struct {
	Page     int64 ` json:"page"`
	PageSize int64 ` json:"pageSize"`
}

type GetProductListResp struct {
	Products []*Product `json:"products"` // 商品列表（简略信息）
	Total    int64      `json:"total"`    // 总记录数
	Page     int64      `json:"page"`     // 当前页码
	PageSize int64      `json:"pageSize"` // 每页大小
}

type Product struct {
	ID    int64   `json:"id"`    // 商品ID
	Name  string  `json:"name"`  // 商品名称
	Stock int64   `json:"stock"` // 商品库存
	Price float64 `json:"price"` // 商品价格
}
