// Code generated by goctl. DO NOT EDIT.
// Source: coupons.proto

package server

import (
	"context"

	"jijizhazha1024/go-mall/services/coupons/coupons"
	"jijizhazha1024/go-mall/services/coupons/internal/logic"
	"jijizhazha1024/go-mall/services/coupons/internal/svc"
)

type CouponsServer struct {
	svcCtx *svc.ServiceContext
	coupons.UnimplementedCouponsServer
}

func NewCouponsServer(svcCtx *svc.ServiceContext) *CouponsServer {
	return &CouponsServer{
		svcCtx: svcCtx,
	}
}

// ListCoupons 获取优惠券列表
func (s *CouponsServer) ListCoupons(ctx context.Context, in *coupons.ListCouponsReq) (*coupons.ListCouponsResp, error) {
	l := logic.NewListCouponsLogic(ctx, s.svcCtx)
	return l.ListCoupons(in)
}

// GetCoupon 获取单个优惠券
func (s *CouponsServer) GetCoupon(ctx context.Context, in *coupons.GetCouponReq) (*coupons.GetCouponResp, error) {
	l := logic.NewGetCouponLogic(ctx, s.svcCtx)
	return l.GetCoupon(in)
}

// CreateCoupon 创建优惠券
func (s *CouponsServer) CreateCoupon(ctx context.Context, in *coupons.CreateCouponReq) (*coupons.CreateCouponResp, error) {
	l := logic.NewCreateCouponLogic(ctx, s.svcCtx)
	return l.CreateCoupon(in)
}

// UpdateCoupon 更新优惠券
func (s *CouponsServer) UpdateCoupon(ctx context.Context, in *coupons.UpdateCouponReq) (*coupons.UpdateCouponResp, error) {
	l := logic.NewUpdateCouponLogic(ctx, s.svcCtx)
	return l.UpdateCoupon(in)
}

// DeleteCoupon 删除优惠券
func (s *CouponsServer) DeleteCoupon(ctx context.Context, in *coupons.DeleteCouponReq) (*coupons.DeleteCouponResp, error) {
	l := logic.NewDeleteCouponLogic(ctx, s.svcCtx)
	return l.DeleteCoupon(in)
}

// ListUserCoupons 获取用户优惠券列表
func (s *CouponsServer) ListUserCoupons(ctx context.Context, in *coupons.ListUserCouponsReq) (*coupons.ListUserCouponsResp, error) {
	l := logic.NewListUserCouponsLogic(ctx, s.svcCtx)
	return l.ListUserCoupons(in)
}

// ClaimCoupon 用户领取优惠券
func (s *CouponsServer) ClaimCoupon(ctx context.Context, in *coupons.ClaimCouponReq) (*coupons.ClaimCouponResp, error) {
	l := logic.NewClaimCouponLogic(ctx, s.svcCtx)
	return l.ClaimCoupon(in)
}

// UseCoupon 使用优惠券
func (s *CouponsServer) UseCoupon(ctx context.Context, in *coupons.UseCouponReq) (*coupons.UseCouponResp, error) {
	l := logic.NewUseCouponLogic(ctx, s.svcCtx)
	return l.UseCoupon(in)
}

// ListCouponUsages 获取优惠券使用记录
func (s *CouponsServer) ListCouponUsages(ctx context.Context, in *coupons.ListCouponUsagesReq) (*coupons.ListCouponUsagesResp, error) {
	l := logic.NewListCouponUsagesLogic(ctx, s.svcCtx)
	return l.ListCouponUsages(in)
}
