// Code generated by goctl. DO NOT EDIT.
// Source: coupons.proto

package couponsclient

import (
	"context"

	"jijizhazha1024/go-mall/services/coupons/coupons"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CalculateCouponReq   = coupons.CalculateCouponReq
	CalculateCouponResp  = coupons.CalculateCouponResp
	ClaimCouponReq       = coupons.ClaimCouponReq
	ClaimCouponResp      = coupons.ClaimCouponResp
	Coupon               = coupons.Coupon
	CouponUsage          = coupons.CouponUsage
	CreateCouponReq      = coupons.CreateCouponReq
	CreateCouponResp     = coupons.CreateCouponResp
	DeleteCouponReq      = coupons.DeleteCouponReq
	DeleteCouponResp     = coupons.DeleteCouponResp
	GetCouponReq         = coupons.GetCouponReq
	GetCouponResp        = coupons.GetCouponResp
	ListCouponUsagesReq  = coupons.ListCouponUsagesReq
	ListCouponUsagesResp = coupons.ListCouponUsagesResp
	ListCouponsReq       = coupons.ListCouponsReq
	ListCouponsResp      = coupons.ListCouponsResp
	ListUserCouponsReq   = coupons.ListUserCouponsReq
	ListUserCouponsResp  = coupons.ListUserCouponsResp
	PaginationReq        = coupons.PaginationReq
	UpdateCouponReq      = coupons.UpdateCouponReq
	UpdateCouponResp     = coupons.UpdateCouponResp
	UserCoupon           = coupons.UserCoupon

	Coupons interface {
		// ListCoupons 获取优惠券列表
		ListCoupons(ctx context.Context, in *ListCouponsReq, opts ...grpc.CallOption) (*ListCouponsResp, error)
		// GetCoupon 获取单个优惠券
		GetCoupon(ctx context.Context, in *GetCouponReq, opts ...grpc.CallOption) (*GetCouponResp, error)
		// CreateCoupon 创建优惠券
		CreateCoupon(ctx context.Context, in *CreateCouponReq, opts ...grpc.CallOption) (*CreateCouponResp, error)
		// UpdateCoupon 更新优惠券
		UpdateCoupon(ctx context.Context, in *UpdateCouponReq, opts ...grpc.CallOption) (*UpdateCouponResp, error)
		// DeleteCoupon 删除优惠券
		DeleteCoupon(ctx context.Context, in *DeleteCouponReq, opts ...grpc.CallOption) (*DeleteCouponResp, error)
		// ClaimCoupon 用户领取优惠券
		ClaimCoupon(ctx context.Context, in *ClaimCouponReq, opts ...grpc.CallOption) (*ClaimCouponResp, error)
		// ListUserCoupons 获取用户优惠券列表
		ListUserCoupons(ctx context.Context, in *ListUserCouponsReq, opts ...grpc.CallOption) (*ListUserCouponsResp, error)
		// CalculateCoupon 使用优惠券
		CalculateCoupon(ctx context.Context, in *CalculateCouponReq, opts ...grpc.CallOption) (*CalculateCouponResp, error)
		// ListCouponUsages 获取优惠券使用记录
		ListCouponUsages(ctx context.Context, in *ListCouponUsagesReq, opts ...grpc.CallOption) (*ListCouponUsagesResp, error)
	}

	defaultCoupons struct {
		cli zrpc.Client
	}
)

func NewCoupons(cli zrpc.Client) Coupons {
	return &defaultCoupons{
		cli: cli,
	}
}

// ListCoupons 获取优惠券列表
func (m *defaultCoupons) ListCoupons(ctx context.Context, in *ListCouponsReq, opts ...grpc.CallOption) (*ListCouponsResp, error) {
	client := coupons.NewCouponsClient(m.cli.Conn())
	return client.ListCoupons(ctx, in, opts...)
}

// GetCoupon 获取单个优惠券
func (m *defaultCoupons) GetCoupon(ctx context.Context, in *GetCouponReq, opts ...grpc.CallOption) (*GetCouponResp, error) {
	client := coupons.NewCouponsClient(m.cli.Conn())
	return client.GetCoupon(ctx, in, opts...)
}

// CreateCoupon 创建优惠券
func (m *defaultCoupons) CreateCoupon(ctx context.Context, in *CreateCouponReq, opts ...grpc.CallOption) (*CreateCouponResp, error) {
	client := coupons.NewCouponsClient(m.cli.Conn())
	return client.CreateCoupon(ctx, in, opts...)
}

// UpdateCoupon 更新优惠券
func (m *defaultCoupons) UpdateCoupon(ctx context.Context, in *UpdateCouponReq, opts ...grpc.CallOption) (*UpdateCouponResp, error) {
	client := coupons.NewCouponsClient(m.cli.Conn())
	return client.UpdateCoupon(ctx, in, opts...)
}

// DeleteCoupon 删除优惠券
func (m *defaultCoupons) DeleteCoupon(ctx context.Context, in *DeleteCouponReq, opts ...grpc.CallOption) (*DeleteCouponResp, error) {
	client := coupons.NewCouponsClient(m.cli.Conn())
	return client.DeleteCoupon(ctx, in, opts...)
}

// ClaimCoupon 用户领取优惠券
func (m *defaultCoupons) ClaimCoupon(ctx context.Context, in *ClaimCouponReq, opts ...grpc.CallOption) (*ClaimCouponResp, error) {
	client := coupons.NewCouponsClient(m.cli.Conn())
	return client.ClaimCoupon(ctx, in, opts...)
}

// ListUserCoupons 获取用户优惠券列表
func (m *defaultCoupons) ListUserCoupons(ctx context.Context, in *ListUserCouponsReq, opts ...grpc.CallOption) (*ListUserCouponsResp, error) {
	client := coupons.NewCouponsClient(m.cli.Conn())
	return client.ListUserCoupons(ctx, in, opts...)
}

// CalculateCoupon 使用优惠券
func (m *defaultCoupons) CalculateCoupon(ctx context.Context, in *CalculateCouponReq, opts ...grpc.CallOption) (*CalculateCouponResp, error) {
	client := coupons.NewCouponsClient(m.cli.Conn())
	return client.CalculateCoupon(ctx, in, opts...)
}

// ListCouponUsages 获取优惠券使用记录
func (m *defaultCoupons) ListCouponUsages(ctx context.Context, in *ListCouponUsagesReq, opts ...grpc.CallOption) (*ListCouponUsagesResp, error) {
	client := coupons.NewCouponsClient(m.cli.Conn())
	return client.ListCouponUsages(ctx, in, opts...)
}
