// Code generated by goctl. DO NOT EDIT.
package types

type CouponItemResp struct {
	ID             string
	Name           string
	Type           uint8
	Value          int32
	MinAmount      int32
	StartTime      int64
	EndTime        int64
	TotalCount     int32
	RemainingCount int32
	CreatedAt      int64
	UpdatedAt      int64
}

type CouponListReq struct {
	Page     uint32
	PageSize uint32
	Type     uint8 // 优惠卷类型
}

type CouponListResp struct {
	CouponList []CouponItemResp
}
