// Code generated by goctl. DO NOT EDIT.
package types

type CouponItemReq struct {
	ID string `path:"id"`
}

type CouponItemResp struct {
	ID             string `json:"id"`
	Name           string `json:"name"`
	Type           uint8  `json:"type"`
	Value          string `json:"value"`
	MinAmount      string `json:"min_amount"`
	StartTime      string `json:"start_time"`
	EndTime        string `json:"end_time"`
	TotalCount     uint64 `json:"total_count"`
	RemainingCount uint64 `json:"remaining_count"`
	CreatedAt      string `json:"created_at"`
	UpdatedAt      string `json:"updated_at"`
}

type CouponListReq struct {
	Page     uint32 `form:"page,default=1"`
	PageSize uint32 `form:"size,default=10"`
	Type     uint8  `form:"type,optional"` // 优惠卷类型
}

type CouponListResp struct {
	CouponList []CouponItemResp `json:"coupon_list"`
}
