// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.5

package handler

import (
	"net/http"

	"jijizhazha1024/go-mall/apis/carts/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/add",
				Handler: CreateCartItemHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/delete",
				Handler: DeleteCartItemHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/get",
				Handler: CartItemListHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/update",
				Handler: UpdateCartItemHandler(serverCtx),
			},
		},
		rest.WithPrefix("/douyin/carts"),
	)
}
