// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.6

package types

type CartInfoResponse struct {
	Id        int32 `json:"id"`
	UserId    int32 `json:"user_id"`
	ProductId int32 `json:"product_id"`
	Quantity  int32 `json:"quantity"`
	Checked   bool  `json:"checked"`
}

type CartItemListResp struct {
	Total    int32               `json:"total"`
	CartInfo []*CartInfoResponse `json:"cart_info"`
}

type CreateCartReq struct {
	UserId       int32   `json:"user_id"`
	ProductId    int32   `json:"product_id"`
	ProductName  string  `json:"product_name"`
	ProuctImage  string  `json:"prouct_image"`
	ProductPrice float32 `json:"product_price"`
	Quantity     int32   `json:"quantity"`
	Checked      bool    `json:"checked"`
}

type CreateCartResp struct {
	Id int32 `json:"id"`
}

type DeleteCartReq struct {
	Id           int32   `json:"id"`
	UserId       int32   `json:"user_id"`
	ProductId    int32   `json:"product_id"`
	ProductName  string  `json:"product_name"`
	ProuctImage  string  `json:"prouct_image"`
	ProductPrice float32 `json:"product_price"`
	Quantity     int32   `json:"quantity"`
	Checked      bool    `json:"checked"`
}

type DeleteCartResp struct {
	Success bool `json:"success"`
}

type SubCartReq struct {
	UserId       int32   `json:"user_id"`
	ProductId    int32   `json:"product_id"`
	ProductName  string  `json:"product_name"`
	ProuctImage  string  `json:"prouct_image"`
	ProductPrice float32 `json:"product_price"`
	Quantity     int32   `json:"quantity"`
	Checked      bool    `json:"checked"`
}

type SubCartResp struct {
	Id int32 `json:"id"`
}

type UserInfo struct {
	Id int32
}
