// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.5

package types

type CartInfoResponse struct {
	Id        int32 `json:"id"`
	UserId    int32 `json:"user_id"`
	ProductId int32	`json:"product_id"`
	Quantity  int32 `json:"quantity"`
	Checked   bool  `json:"checked"`
}

type CartItemListResponse struct {
	Total int32               `json:"total"`
	Data  []*CartInfoResponse `json:"data"`
}

type CartItemRequest struct {
	Id           int32 	`json:"id"`
	UserId       int32	`json:"user_id"`
	ProductId    int32	`json:"product_id"`
	ProductName  string	`json:"product_name"`
	ProuctImage  string	`json:"prouct_image"`
	ProductPrice float32`json:"product_price"`
	Quantity     int32	`json:"quantity"`
	Checked      bool	`json:"checked"`
}

type EmptyCartResponse struct {
}

type UserInfo struct {
	Id int32
}
type ShopCartItemForm struct {
	ProductId int32 `json:"product_id" binding:"required"`
	Quantity int32 `json:"quantity" binding:"required,min=1"`
}

type ShopCartItemUpdateForm struct {
	Quantity int32 `json:"quantity" binding:"required,min=1"`
	Checked *bool `json:"checked"`
}